<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVp0PPeK\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVp0PPeK/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVp0PPeK.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVp0PPeK\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVp0PPeK\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Vp0PPeK',
    'container.build_id' => 'c862404d',
    'container.build_time' => 1542710893,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVp0PPeK');
