<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHwtTxzG\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHwtTxzG/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHwtTxzG.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHwtTxzG\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerHwtTxzG\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'HwtTxzG',
    'container.build_id' => '8fe1cdbf',
    'container.build_time' => 1543584236,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHwtTxzG');
