<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKfDYOkC\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKfDYOkC/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKfDYOkC.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKfDYOkC\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKfDYOkC\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KfDYOkC',
    'container.build_id' => 'ac668598',
    'container.build_time' => 1542897664,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKfDYOkC');
